# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis
  - pip install coverage codecov xfail
script:
  - tox
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coverage erase && PYTHONPATH=${TRAVIS_BUILD_DIR} python -m coverage run --source syncer -m unittest discover syncer && codecov; fi
