# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36,coverage,flake8,mypy,codecov
    - python: 3.7-dev
      env: TOXENV=py37
    - python: pypy3
      env: TOXENV=pypy3

install:
  - pip install tox

script:
  - tox
